tinyMCE.init({
	theme : "advanced",
	language : "en",
	mode : "none",
	gecko_spellcheck : "true",
	editor_selector : "mce_editable",
	document_base_url : "<?php echo JURI::root();?>",
	entities : "60,lt,62,gt",
	relative_urls : 1,
	remove_script_host : false,
	invalid_elements : "applet",
	extended_valid_elements : "a[class|name|href|target|title|onclick|rel],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],,hr[id|title|alt|class|width|size|noshade]",
	theme_advanced_toolbar_location : "top",
	directionality: "ltr",
	force_br_newlines : "true",
	force_p_newlines : "false",
	content_css : "<?php echo JURI::root().'templates/system/css/editor.css' ?>",
	debug : false,
	cleanup : true,
	cleanup_on_startup : false,
	safari_warning : false,
	plugins : "advlink, advimage, searchreplace,insertdatetime,media,advhr,table,fullscreen,directionality,style",
	theme_advanced_buttons1_add : "insertdate,inserttime,fontselect,media,ltr,rtl,absolute,forecolor",
	theme_advanced_buttons2_add : "",
	theme_advanced_buttons3_add : "advhr,tablecontrols,fullscreen,styleprops",
	theme_advanced_disable : "help",
	plugin_insertdate_dateFormat : "%Y-%m-%d",
	plugin_insertdate_timeFormat : "%H:%M:%S"
});
